### ISSUE TITLE
Style Messages like a Messenger

### ISSUE THREAD

**Issue by csellis** [csellis/all-hands#3]
- [ ] Detect if it's the user's own message and display on left (use the user store)
- [ ] Add typical styling and sort based off created_at
- [ ] You may find using a flex column reverse sorted helpful [https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items)

**Comment by manojku1803** [comment]
Please tell what to do?

**Comment by csellis** [comment]
@manojku1803 Sure mate, You still interested?

**Comment by csellis** [comment]
Closed with #8
